services:
  # for development purposes
  dev:
    build: .
    volumes:
      - ./data:/data
    environment:
      - KBC_DATADIR=/data

  # use to run flake8 and unittests checks
  test:
    build: .
    user: 1000:1000
    volumes:
      - ./data:/data
    environment:
      - KBC_DATADIR=/data
    command:
      - /bin/sh
      - /code/scripts/build_n_test.sh
